# -*- coding: utf-8 -*-
"""01_intro_python (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XEVM3vx4lZedr4xdB_nUJE7S2JdYSQST

# Jour 2 - Introduction pratique à Python

**Workshop d'intégration ESGI - Campus Skolae Rouen**

Bienvenue ! Ici, pas de long cours théorique : on apprend en **pratiquant pas à pas**.
Ce notebook vous guide à votre rythme. Aucune installation : tout s'exécute directement dans votre navigateur grâce à **Google Colab**.

> **Règle d'or :** Cliquez dans une cellule de code (fond gris) puis appuyez sur **Maj + Entrée** (ou sur le bouton ▶️ de lecture) pour l'exécuter.
> Exécutez toujours les cellules **dans l'ordre**, de haut en bas !

## 0. Prise en main : afficher du texte avec `print()`
La fonction `print(...)` permet à votre programme de vous parler et d'afficher des messages à l'écran.
Exécutez la cellule ci-dessous pour voir le résultat.
"""

print("Bonjour, je commence Python aujourd'hui !")

"""### Question 0.1 : À vous de jouer !
Modifiez le code ci-dessous pour afficher votre prénom et votre école.
Exemple attendu : `Je m'appelle Alex et je suis à l'ESGI !`
"""

# TODO : écrivez votre propre message entre guillemets avec print(...)
print("Je m'appelle Lucas et je suis à l'ESGI !")

"""### Question 0.2 : Observation (Texte vs Calcul)
À votre avis, quelle est la différence entre `print(10 + 5)` et `print("10 + 5")` ?
Exécutez la cellule suivante pour observer.
"""

print("Calcul mathématique :", 10 + 5)
print("Texte brut (entre guillemets) :", "10 + 5")

"""---
## 1. Les variables : les boîtes à mémoire
Une variable est comme une **boîte étiquetée** dans la mémoire de l'ordinateur.
- Le nom de la variable est l'étiquette (à gauche du signe `=`).
- La valeur stockée est ce qu'on met dans la boîte (à droite du `=`).
"""

nom = "Marie"
age = 18
print(nom, "a", age, "ans")

"""### Question 1.1 : Stocker des informations
Créez une variable `ecole` contenant `"ESGI"` et une variable `ville` contenant `"Rouen"`.
Affichez ensuite la phrase : `Bienvenue à l'ESGI campus de Rouen !`
"""

# TODO : créez les deux variables ecole et ville
# TODO : affichez la phrase avec print(...)

ecole = "ESGI"

ville =  "Rouen"

print("Bienvenue à l'ESGI campus de Rouen !")

"""### Question 1.2 : Modifier le contenu d'une boîte
Une variable peut changer de valeur à tout moment !
Créez une variable `score_alerte` valant `10`.
Puis, à la ligne suivante, donnez-lui la valeur `25`.
Affichez la variable : quelle valeur s'affiche ?
"""

# TODO : initialisez score_alerte à 10, puis modifiez-le à 25, et affichez-le

score_alerte = 10

score_alerte = 25

print(score_alerte)

"""### Question 1.3 : Calculer avec des variables
Créez une variable `nb_etudiants` valant `17` et une variable `nb_groupes` valant `4`.
Affichez le nombre moyen d'étudiants par groupe en divisant `nb_etudiants / nb_groupes`.
"""



# TODO : créez les deux variables et affichez leur division avec print(...)

nb_etudiants = 17

nb_groupes = 4

print(nb_etudiants / nb_groupes)

"""---
## 2. Les types de données (et le typage dynamique)
En Python, on manipule principalement 4 types de base :
- `str` (*string*) : du texte entre guillemets (`"bonjour"`, `"phishing"`).
- `int` (*integer*) : des nombres entiers (`18`, `-5`, `400`).
- `float` : des nombres à virgule / décimaux (`3.14`, `0.75`).
- `bool` (*boolean*) : les vérités logiques, uniquement `True` (vrai) ou `False` (faux).

En Python, le type est **deviné automatiquement** et peut changer au fil de l'exécution (typage dynamique).
"""

x = 5
print(x, "est de type :", type(x))

x = "maintenant je suis du texte !"
print(x, "est de type :", type(x))

"""### Question 2.1 : Découvrir les types
Affichez le type de chacune des 4 valeurs ci-dessous à l'aide de la fonction `type(...)` :
- `3.14`
- `True`
- `"phishing"`
- `42`
"""

# TODO : utilisez print(type(...)) pour chacune des 4 valeurs

print(type(3.14))

print(type(True))

print(type("phising"))

print(type(42))

"""### Question 2.2 : Piège classique (Texte vs Nombre)
Observez ce qui se passe quand on multiplie du texte par 2, comparé à un nombre multiplié par 2.
"""

nombre = 20
texte = "20"

print("Nombre * 2 =", nombre * 2)   # calcul arithmétique : 40
print("Texte * 2  =", texte * 2)    # répétition du texte : "2020" !

"""---
## 3. Manipuler le texte (Chaînes de caractères)
En cybersécurité, un e-mail ou un SMS suspect est avant tout du **texte**.
Savoir inspecter et nettoyer du texte est la première compétence de l'analyste SOC !
"""

message = "URGENT : cliquez ici pour gagner un cadeau"

print("En minuscules :", message.lower())
print("Nombre de caractères (longueur) :", len(message))
print("Le mot 'urgent' est-il présent ?", "urgent" in message.lower())

"""### Question 3.1 : Calculer une longueur avec `len()`
Calculez et affichez le nombre de caractères de l'e-mail d'alerte suivant :
`"Votre compte bancaire a été temporairement suspendu pour des raisons de sécurité."`
"""

alerte = "Votre compte bancaire a été temporairement suspendu pour des raisons de sécurité."
# TODO : affichez sa longueur avec len(...)

print(len(alerte))

"""### Question 3.2 (Exercice 2.1) : Rechercher un mot avec `in`
Vérifiez si le mot `"cadeau"` est présent dans la variable `message` définie plus haut.
(Résultat attendu : `True`).
"""

# Exercice 2.1
# TODO : vérifiez si "cadeau" est dans message.lower()
# Astuce : utilisez l'opérateur 'in'

print("cadeau" in message.lower())

"""### Question 3.3 : Pourquoi passer en minuscules avec `.lower()` ?
Exécutez la cellule ci-dessous pour comprendre le piège de la casse (majuscules/minuscules).
"""

texte_test = "URGENT : votre facture est en attente"

print("Sans .lower() :", "urgent" in texte_test)          # False ! Car 'urgent' != 'URGENT'
print("Avec .lower() :", "urgent" in texte_test.lower())  # True !

"""### Question 3.4 : Remplacer du texte avec `.replace()`
Dans un centre de sécurité, on neutralise parfois les liens dangereux pour éviter qu'un utilisateur clique dessus.
Utilisez la méthode `.replace("http://", "[LIEN DÉSACTIVÉ]")` sur l'e-mail ci-dessous et affichez le résultat.
"""

lien_piege = "Veuillez vous connecter sur http://banque-securite-connexion.ru/login"
# TODO : remplacez "http://" par "[LIEN DÉSACTIVÉ]" grâce à .replace(...)
# TODO : affichez le message neutralisé


lien_piege.replace("http://", "[LIEN DÉSACTIVÉ]")

"""---
## 4. Les listes (collections ordonnées)
Une liste permet de ranger plusieurs éléments dans une seule variable, entre crochets `[...]`.
On peut accéder à chaque élément par son numéro (son **indice**), en commençant toujours par **0** !
"""

mots_suspects = ["urgent", "cadeau", "gagner", "mot de passe", "cliquez"]

print("Premier mot (indice 0) :", mots_suspects[0])
print("Deuxième mot (indice 1) :", mots_suspects[1])
print("Dernier mot (indice -1) :", mots_suspects[-1])
print("Nombre total de mots   :", len(mots_suspects))

"""### Question 4.1 : Créer sa propre liste de surveillance
Créez une liste nommée `marques_cibles` contenant 4 noms de marques souvent usurpées par les cybercriminels :
`"paypal"`, `"ameli"`, `"netflix"`, `"laposte"`.
Affichez cette liste.
"""

# TODO : créez la liste marques_cibles avec les 4 marques entre crochets
# TODO : affichez-la avec print(...)

marques_cibles = ["paypal", "ameli", "netflix", "laposte"]
print(marques_cibles)

"""### Question 4.2 : Accéder aux éléments d'une liste
Affichez le **premier** élément de `marques_cibles` (indice 0) et le **dernier** élément (indice -1).
"""

# TODO : affichez le premier élément puis le dernier de marques_cibles

print(marques_cibles[0])

"""### Question 4.3 : Ajouter un élément avec `.append()`
Ajoutez le mot `"banque"` à la liste `mots_suspects`.
Affichez la liste mise à jour ainsi que sa nouvelle longueur avec `len(...)`.
"""

# TODO : ajoutez "banque" à mots_suspects avec la méthode .append(...)
# TODO : affichez la liste et sa longueur

mots_suspects.append("banque")

print(mots_suspects, len(mots_suspects))

"""### Question 4.4 : Vérifier la présence dans une liste avec `in`
L'opérateur `in` fonctionne aussi sur les listes !
Vérifiez si `"facture"` est déjà présent dans `mots_suspects` (résultat attendu : `False`).
"""

# TODO : testez si "facture" est dans mots_suspects

print("facture" in mots_suspects)

"""---
## 5. Les conditions (`if` / `elif` / `else`) : prendre des décisions
Un programme de détection doit réagir différemment selon la dangerosité d'un message.
La structure conditionnelle permet d'exécuter du code **seulement si** une condition est vraie.

> ⚠️ **Attention à l'indentation :** En Python, les lignes de code sous un `if` ou un `else` doivent être décalées de **4 espaces** vers la droite. C'est ce décalage qui indique à Python que ces lignes appartiennent au bloc !
"""

texte = "urgent cliquez ici"

if "urgent" in texte:
    print("⚠️ Attention : e-mail suspect détecté !")
else:
    print("✅ Aucun indice d'urgence : message à priori normal.")

"""### Question 5.1 : Première condition
Soit la variable `email_test = "Félicitations, vous venez de gagner un iPhone !"`.
Écrivez une condition :
- Si `"gagner"` est présent dans `email_test.lower()` -> afficher `"🚨 Suspicion d'escroquerie !"`
- Sinon -> afficher `"✅ Message apparemment légitime."`
"""

email_test = "Félicitations, vous venez de gagner un iPhone !"
# TODO : écrivez le if / else pour tester si "gagner" est dans email_test.lower()

if "gagner" in email_test.lower() == True:
  print("🚨 Suspicion d'escroquerie !")
else:
  print("✅ Message apparemment légitime.")

"""### Question 5.2 : Les combinaisons logiques (`and` / `or`)
Dans la réalité, un e-mail est souvent suspect s'il combine plusieurs éléments.
- `and` : les deux conditions doivent être vraies en même temps.
- `or` : au moins une des deux conditions doit être vraie.

Testez si le message ci-dessous contient `"urgent"` **ET** `"virement"`.
"""

message_banque = "URGENT : virement bancaire bloqué par la sécurité"
# TODO : utilisez un if avec 'and' pour vérifier la présence des 2 mots à la fois

if "urgent" and "virement" in message_banque:
  print("escroquerie")

"""### Question 5.3 : Graduer la menace avec `elif` (sinon si)
Soit une variable `nb_alertes = 2`.
Écrivez une structure conditionnelle à 3 niveaux :
- Si `nb_alertes >= 3` : afficher `"🔴 NIVEAU ROUGE : Attaque critique"`
- Sinon si (`elif`) `nb_alertes >= 1` : afficher `"🟠 NIVEAU ORANGE : Message suspect"`
- Sinon (`else`) : afficher `"🟢 NIVEAU VERT : Message sain"`
"""

nb_alertes = 2
# TODO : écrivez le if / elif / else

if nb_alertes >= 3:
  print("🔴 NIVEAU ROUGE : Attaque critique")
elif nb_alertes >= 1:
  print("🟠 NIVEAU ORANGE : Message suspect")
else:
  print("🟢 NIVEAU VERT : Message sain")

"""---
## 6. Les boucles `for` : répéter une action automatiquement
Au lieu d'écrire 10 conditions `if` à la main pour chaque mot de notre liste, une boucle `for` parcourt automatiquement la liste, élément par élément !
"""

for mot in mots_suspects:
    print("Inspection du mot :", mot)

"""### Question 6.1 : Boucle simple
Parcourez votre liste `marques_cibles` avec une boucle `for`.
Pour chaque marque, affichez son nom en MAJUSCULES grâce à la méthode `.upper()`.
"""

# TODO : faites une boucle for marque in marques_cibles:
#        et affichez marque.upper()

for marque in marques_cibles:
  print(marque.upper())

"""### Question 6.2 (Exercice 2.2) : Boucle + Condition (Repérer les mots suspects)
Soit la phrase : `texte_recu = "urgent vous devez cliquez maintenant pour valider votre compte"`.
Parcourez `mots_suspects` avec une boucle `for`.
À chaque tour, si le mot est présent dans `texte_recu`, affichez : `Mot suspect trouvé : <mot>`.
*(Mots attendus : "urgent", "cliquez")*
"""

# Exercice 2.2
texte_recu = "urgent vous devez cliquez maintenant pour valider votre compte"

# TODO : parcourez mots_suspects
# TODO : si mot in texte_recu, affichez-le

print(mots_suspects)

for mots in mots_suspects:
  if mots in texte_recu:
    print(mots)

"""### Question 6.3 : Compter les alertes avec un accumulateur
Pour savoir combien de mots suspects ont été trouvés au total, on utilise une variable **compteur** :
1. On démarre avec `total = 0` avant la boucle.
2. Chaque fois qu'on trouve un mot suspect, on ajoute 1 : `total = total + 1`.
3. Après la boucle, on affiche le total.

Complétez le code ci-dessous.
"""

texte_recu = "urgent vous devez cliquez maintenant pour valider votre compte"

total = 0
# TODO : écrivez la boucle for qui incrémente total de 1 pour chaque mot trouvé
# TODO : affichez total à la fin

for mots in mots_suspects:
  if mots in texte_recu:
    total += 1
    print(mots, total)
print("total :", total)

"""### Question 6.4 : Collecter les mots trouvés dans une nouvelle liste
Au lieu de simplement compter, on veut enregistrer les mots découverts dans une liste `trouves = []`.
À chaque mot suspect détecté, ajoutez-le avec `trouves.append(mot)`.
Affichez la liste finale des alertes.
"""

texte_recu = "urgent vous devez cliquez maintenant pour valider votre compte"
trouves = []

# TODO : boucle for + if, puis trouves.append(mot)
# TODO : affichez trouves

for mots in mots_suspects:
  if mots in texte_recu:
    trouves.append(mots)
print(trouves)

"""---
## 7. Les fonctions : fabriquer nos propres outils réutilisables
Une fonction est une **recette** ou une **machine** :
- Elle a un nom (après le mot-clé `def`).
- Elle reçoit des données en entrée (les **paramètres** entre parenthèses).
- Elle renvoie un résultat avec le mot-clé `return`.

> 💡 **Différence essentielle :**
> - `print(...)` sert uniquement à afficher un texte dans la console pour l'humain.
> - `return ...` renvoie la vraie valeur à votre programme pour qu'on puisse la stocker dans une variable ou faire un test !
"""

def saluer(prenom):
    return "Bienvenue dans l'équipe de cyber-défense, " + prenom + " !"

message_accueil = saluer("Lucas")
print(message_accueil)

"""### Question 7.1 : Une première fonction d'alerte
Écrivez une fonction `est_un_lien_douteux(url)` qui prend en paramètre une chaîne `url`.
- Si `url` commence par `"http://"` ou contient `"bit.ly"`, elle renvoie `True`.
- Sinon, elle renvoie `False`.
"""

def est_un_lien_douteux(url):
    if "http://" in url or "bit.ly" in url:
      return True
    else:
      return False

print(est_un_lien_douteux("http://serveur-pirate.ru/login"))  # attendu : True
print(est_un_lien_douteux("https://esgi.fr"))                  # attendu : False

"""### Question 7.2 : La fonction `compter_mots_suspects`
Voici la fonction qui résume tout ce qu'on a vu : elle prend un e-mail en entrée, le passe en minuscules, parcourt notre liste de mots suspects, et renvoie le total.
"""

def compter_mots_suspects(texte):
    total = 0
    for mot in mots_suspects:
        if mot in texte.lower():
            total = total + 1
    return total

# Test sur un e-mail avec 3 mots suspects
print("Score :", compter_mots_suspects("URGENT cliquez pour un cadeau"))

"""### Question 7.3 : Tester la fonction sur différents e-mails
Testez la fonction `compter_mots_suspects` sur deux e-mails différents :
1. Un faux message de banque : `"Alerte banque : cliquez pour réactiver votre carte"`
2. Un e-mail normal entre collègues : `"Bonjour, on se retrouve à la cafétéria à midi ?"`
"""

email_banque = "Alerte banque : cliquez pour réactiver votre carte"
email_normal = "Bonjour, on se retrouve à la cafétéria à midi ?"

print(mots_suspects)

print(compter_mots_suspects(email_banque))
print(compter_mots_suspects(email_normal))

# TODO : affichez le score de compter_mots_suspects pour chacun des deux e-mails

"""---
## 8. Le Grand Défi : Construire notre premier détecteur autonome !
Nous avons désormais tous les blocs nécessaires pour assembler un détecteur complet.
"""



# Exercice 2.3
def ponctuation(texte):
    return "!!!" not in texte

def est_suspect(texte):
    if compter_mots_suspects(texte) >= 2:
      return True
    elif ponctuation(texte) == False:
      return True
    else:
      return False

print("Test 1 (phishing) :", est_suspect("urgent cliquez pour un cadeau")) # attendu : True
print("Test 2 (légitime) :", est_suspect("bonjour, réunion demain à 14h"))  # attendu : False
print("Test 3 (légitime) :", est_suspect("bonjour, réunion demain à 14h !!!"))  # attendu : True

"""### Défi 8.1 (Exercice 2.3) : La fonction `est_suspect(texte)`
Écrivez une fonction `est_suspect(texte)` qui :
1. Calcule le nombre de mots suspects grâce à `compter_mots_suspects(texte)`.
2. Renvoie `True` si ce nombre est **supérieur ou égal à 2** (`>= 2`).
3. Renvoie `False` sinon.

### Défi 8.2 (Bonus) : Le tableau de bord du SOC !
Créons une fonction d'analyse complète `analyser_email_complet(email)` qui produit un rapport clair pour l'équipe de sécurité :
- Affiche le message analysé
- Affiche les mots suspects détectés
- Indique si un lien douteux (`http://` ou `bit.ly`) a été repéré
- Conclut avec un verdict : `"🚨 ALERTE PHISHING"` ou `"✅ E-MAIL SÉCURISÉ"`
"""

def analyser_email_complet(email):
    print("Message analysé :", email)

    mots_trouves = [];
    total = compter_mots_suspects(email)

    for mots in mots_suspects:
      if mots in email.lower():
        mots_trouves.append(mots)

    if est_suspect(email):
      print("Il y a", total ,"mots suspects trouves et les mots sont :", mots_trouves)
    else:
      print("Il y a", total ,"mots suspects trouves")

    lien_douteux = est_un_lien_douteux(email)

    if (lien_douteux is True):
      print("Un lieu douteux a ete trouve")
    else:
      print("Aucun lieu douteux n'a ete trouve")

    if total == 0 and lien_douteux == False:
      print("Resultat : ✅ E-MAIL SÉCURISÉ")
    elif total >= 1 and lien_douteux:
      print("Resultat :🚨 ALERTE PHISHING")
    else:
      print("Resultat : POTENTIEL PHISHING")




# Testez votre fonction avec un e-mail suspect et un e-mail normal
analyser_email_complet("URGENT : cliquez sur http://bit.ly/update-banque pour réclamer votre cadeau !")
print()
analyser_email_complet("Salut l'équipe, n'oubliez pas notre point projet à 10h en salle B12.")
print()
analyser_email_complet("URGENT : cliquez pour réclamer votre cadeau !")
print()
analyser_email_complet("http://bit.ly/update")

"""---
## Bravo pour cette matinée !
En quelques heures seulement, vous avez appris :
- Les **variables**, les **calculs** et les **types de données** (`str`, `int`, `float`, `bool`)
- Les manipulations de **texte** (`.lower()`, `len()`, `.replace()`, `in`)
- Les **listes** et la méthode `.append()`
- Les **conditions** (`if` / `elif` / `else`) et les opérateurs logiques (`and` / `or`)
- Les **boucles** (`for`) et les accumulateurs
- Les **fonctions** (`def`, arguments, `return`)
- Et vous avez construit votre **premier détecteur de phishing basé sur des règles** !

### Pourquoi passer à l'Intelligence Artificielle au Jour 3 ?
Réfléchissez à notre programme : il ne repère que les mots qui sont **exactement** dans notre liste écrite à la main.
Si un pirate utilise des synonymes ou des fautes volontaires (*"urgemmnt"*, *"somme d'argent"* au lieu de *"cadeau"*), notre détecteur manuel ne verra rien !

Au **Jour 3**, nous allons confier **400 e-mails** à une **Intelligence Artificielle (Machine Learning)** : la machine va analyser les fréquences de mots et apprendre **toute seule** à distinguer le vrai du faux !
"""