# -*- coding: utf-8 -*-
"""02_detection_phishing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZpQU8q5KTIMUu-BZa1HwL4grQwO-TQqn

# Jour 3 - Construire un détecteur de phishing par IA

**Workshop d'intégration ESGI - Campus Skolae Rouen**

Bienvenue dans le cœur du workshop !
Au **Jour 2**, nous avons écrit des règles manuelles (`est_suspect`). Mais concevoir une liste de mots à la main est fastidieux et incomplet.

Aujourd'hui, nous changeons d'échelle : nous allons utiliser la **Data Science** et le **Machine Learning (IA)** pour que l'ordinateur apprenne **tout seul** à reconnaître le phishing à partir de 400 exemples réels !

### Notre feuille de route :
1. **Découverte de Pandas & des DataFrames :** charger et explorer un tableau de données.
2. **Exploration de la structure :** dimensions, colonnes, types et équilibre des classes.
3. **Filtrage conditionnel :** extraire et inspecter des e-mails suspects ou légitimes.
4. **Ingénierie des données cyber :** créer de nouvelles colonnes (longueur, détection de motifs).
5. **Séparation Apprentissage / Test :** la méthode rigoureuse pour évaluer une IA.
6. **Entraînement du modèle :** transformer le texte en chiffres (TF-IDF) et apprendre.
7. **Évaluation & Analyse d'hésitation :** mesurer le score et repérer où l'IA hésite.
8. **Interprétation du modèle :** quels mots trahissent le phishing ?

---
## 1. Qu'est-ce qu'un DataFrame ? Charger les données avec Pandas
En Python, la bibliothèque reine pour manipuler des données est **Pandas**.
Son objet principal s'appelle un **DataFrame** :
- C'est l'équivalent d'un **tableau Excel** ou d'une table SQL.
- Il est organisé en **lignes** (chaque ligne représente un e-mail) et en **colonnes** (les informations sur cet e-mail : son texte, sa catégorie, etc.).

Chargeons notre jeu de données `emails_mini.csv` dans un DataFrame nommé `df`.
"""

import os
import pandas as pd

# Recherche du fichier en local ou téléchargement depuis GitHub
DATA_URL = "/emails_mini.csv"

for chemin in ["emails_mini.csv", "data/emails_mini.csv", "../data/emails_mini.csv"]:
    if os.path.exists(chemin):
        df = pd.read_csv(chemin)
        break
else:
    df = pd.read_csv(DATA_URL)

print("Fichier chargé avec succès dans la variable 'df' !")

"""### Question 1.1 : Afficher les premières lignes avec `.head()`
La méthode `df.head(n)` permet de visualiser les $n$ premières lignes du tableau (par défaut 5).
Exécutez la cellule ci-dessous pour voir à quoi ressemble notre DataFrame.
"""

df.head()

"""### Question 1.2 : Afficher les dernières lignes avec `.tail()`
La méthode `df.tail(n)` fait l'inverse : elle montre la fin du tableau.
Affichez les **3 dernières lignes** du DataFrame.
"""

# TODO : affichez les 3 dernières lignes avec df.tail(...)

df.tail(3)

"""---
## 2. Explorer la structure et la taille du DataFrame
Avant toute modélisation, un analyste en cybersécurité explore toujours ses données pour répondre à des questions fondamentales :
- Combien d'exemples avons-nous ?
- Quelles sont les colonnes disponibles ?
- Les catégories sont-elles équilibrées ?

### Question 2.1 : Dimensions avec `.shape`
L'attribut `df.shape` donne les dimensions sous forme de tuple `(nombre_lignes, nombre_colonnes)`.
Affichez `df.shape` ainsi que la liste des noms de colonnes grâce à `df.columns`.
"""

# TODO : affichez df.shape et df.columns

print(df.shape)
print()
print(df.columns)

"""### Question 2.2 : Accéder à une colonne (Notion de Series)
Dans Pandas, lorsqu'on extrait une seule colonne d'un DataFrame, on obtient une **Series** (une liste étiquetée).
Pour sélectionner une colonne, on utilise les crochets : `df["nom_colonne"]`.

Affichez les 5 premiers éléments de la colonne `"label"`.
"""

# TODO : sélectionnez la colonne "label" et affichez ses 5 premières valeurs avec .head()

df["label"].head(6)

"""### Question 2.3 (Exercice 3.1 - partie 1) : Équilibre des classes avec `.value_counts()`
La colonne `"label"` contient la vérité terrain :
- `1` = tentative de **phishing**
- `0` = e-mail **légitime** (normal)

La méthode `.value_counts()` compte combien de fois chaque valeur apparaît.
Comptez le nombre d'e-mails légitimes et de phishings.
"""

# TODO : utilisez df["label"].value_counts() pour compter le nombre de 0 et de 1

df["label"].value_counts()

"""### Question 2.4 : Calculer les pourcentages
En ajoutant le paramètre `normalize=True` dans `.value_counts()`, Pandas calcule automatiquement les proportions (entre 0 et 1).
Affichez les proportions sous forme de pourcentages en multipliant par 100.
Que constatez-vous sur notre jeu de données ?
"""

# TODO : calculez les pourcentages avec df["label"].value_counts(normalize=True) * 100

df["label"].value_counts(normalize=True) * 100

"""---
## 3. Filtrer et inspecter les e-mails (Masques conditionnels)
Pour isoler une partie des données, on utilise un **filtre conditionnel** (ou filtre booléen) :
`df[condition]`

Exemple : `df[df["label"] == 1]` sélectionne uniquement les lignes où le label vaut 1.

### Question 3.1 : Isoler les phishings et les e-mails légitimes
Créez deux sous-DataFrames :
- `df_phishing` contenant uniquement les phishings (`label == 1`).
- `df_legitime` contenant uniquement les e-mails légitimes (`label == 0`).
Affichez le nombre de lignes de chacun grâce à `len(...)`.
"""

# TODO : créez df_phishing et df_legitime en filtrant sur df["label"]
# TODO : affichez leur taille avec len(...)

df_phishing = df[df["label"] == 1]
df_legitime = df[df["label"] == 0]

print("Email phising = ", len(df_phishing))
print("Email legitime = ", len(df_legitime))

"""### Question 3.2 : Lire des e-mails en texte intégral avec `.iloc`
L'indexeur `.iloc[i]` permet d'accéder à la ligne numéro $i$ (en commençant par 0).
Affichez le texte du premier phishing (`df_phishing["text"].iloc[0]`) et celui du premier e-mail légitime (`df_legitime["text"].iloc[0]`).
"""

# TODO : affichez le premier phishing et le premier e-mail légitime avec .iloc[0]

print(df_phishing["text"].iloc[0])
print(df_legitime["text"].iloc[0])

"""---
## 4. Ingénierie des données cyber (Créer de nouvelles colonnes)
Dans un centre de cyber-défense (SOC), les analystes ne se contentent pas de lire les messages bruts : ils **extraient de nouveaux indicateurs** pour enrichir la détection.

Créons de nouvelles caractéristiques (*features*) directement dans notre DataFrame !

### Question 4.1 : Créer la colonne `longueur`
Dans Pandas, pour appliquer une fonction de texte sur chaque élément d'une colonne, on utilise `.str` :
`df["longueur"] = df["text"].str.len()`

Créez cette colonne et affichez les 5 premières lignes avec `df.head()` pour constater son ajout.
"""

# TODO : créez la colonne df["longueur"] avec df["text"].str.len()
# TODO : affichez df.head()

df["longueur"] = df["text"].str.len()
df.head()

"""### Question 4.2 : Statistiques sur la longueur des e-mails
Calculez :
- La longueur moyenne avec `.mean()`
- La longueur minimale avec `.min()`
- La longueur maximale avec `.max()`
"""

# TODO : calculez la moyenne, le min et le max de df["longueur"]

print("Moyenne : ", df["longueur"].mean())
print("Min : ", df["longueur"].min())
print("Max : ", df["longueur"].max())

"""### Question 4.3 (Enquête cyber) : Les phishings sont-ils plus longs que les e-mails sains ?
Calculez la longueur moyenne séparément pour les e-mails de phishing (`df_phishing`) et pour les e-mails légitimes (`df_legitime`).
Que remarquez-vous ?
"""

# TODO : calculez et comparez la moyenne de df["longueur"] pour label == 1 et label == 0

df_phishing = df[df["label"] == 1]
df_legitime = df[df["label"] == 0]

print("Moyenne longueur phishing :", df_phishing["longueur"].mean())
print("Moyenne longueur legitime :", df_legitime["longueur"].mean())

"""### Question 4.4 : Recherche par mot-clé avec `.str.contains()`
Vérifions notre intuition du Jour 2 : le mot `"urgent"` est-il un bon indicateur de phishing ?
La méthode `df["text"].str.contains("urgent", case=False)` renvoie `True` pour chaque e-mail contenant "urgent" (en ignorant la casse).

Comptez combien d'e-mails au total contiennent `"urgent"` avec `.sum()`.
"""

contient_urgent = df["text"].str.contains("urgent", case=False)
# TODO : affichez le nombre d'e-mails contenant 'urgent' avec .sum()
# TODO : affichez df[contient_urgent]["label"].value_counts()

print(contient_urgent.sum())

df[contient_urgent]["label"].value_counts()

"""---
## 5. Séparer Apprentissage et Test (Train / Test Split)
En Machine Learning, on applique une règle d'or : **on ne teste JAMAIS une IA sur les données qu'elle a utilisées pour apprendre**.
C'est exactement comme un examen à l'école : donner le corrigé aux élèves avant l'épreuve n'évalue pas leur compréhension réelle !

Nous allons donc découper notre DataFrame en deux :
- **Ensemble d'entraînement (Train)** : 75 % des e-mails pour que l'IA découvre les motifs.
- **Ensemble de test (Test)** : 25 % des e-mails, gardés secrets, pour mesurer son efficacité.
"""

from sklearn.model_selection import train_test_split

X = df["text"]    # les données d'entrée (le texte des e-mails)
y = df["label"]   # la réponse attendue (0 ou 1)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=100, stratify=y, random_state=42
)

print("E-mails d'entraînement (Train) :", len(X_train))
print("E-mails de test (Test)          :", len(X_test))

"""### Question 5.1 : Vérification de la stratification
Le paramètre `stratify=y` garantit qu'il y a exactement la même proportion de phishings (50%) dans l'entraînement et dans le test.
Vérifiez cela en exécutant `y_train.value_counts()` et `y_test.value_counts()`.
"""

# TODO : vérifiez y_train.value_counts() et y_test.value_counts()

print(y_train.value_counts())
print()
print(y_test.value_counts())

"""---
## 6. Transformer le texte en chiffres (TF-IDF) et entraîner le modèle
Un algorithme mathématique ne comprend pas les phrases en français ou en anglais : il a besoin de **chiffres**.

1. **TF-IDF (`TfidfVectorizer`)** : transforme chaque e-mail en une suite de nombres. Il mesure l'importance relative de chaque mot.
2. **Régression Logistique (`LogisticRegression`)** : un modèle d'IA simple, robuste et ultra-rapide qui apprend à séparer les messages en deux catégories.
3. **Pipeline (`make_pipeline`)** : relie la transformation TF-IDF et le classifieur dans une chaîne fluide.
"""

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline

modele = make_pipeline(
    TfidfVectorizer(),
    LogisticRegression(max_iter=1000)
)

# C'est ici que l'IA apprend à partir des exemples d'entraînement !
modele.fit(X_train, y_train)

print("✅ Modèle d'IA entraîné avec succès !")

"""---
## 7. Évaluer les performances du modèle
Maintenant que le modèle est entraîné, donnons-lui les 100 e-mails de test (`X_test`) qu'il n'a **jamais vus**.
Nous comparons ses prédictions avec les vraies réponses (`y_test`).

### Question 7.1 (Exercice 3.1 - partie 2) : Calculer le score d'exactitude (Accuracy)
La méthode `modele.score(X_test, y_test)` renvoie la fraction de bonnes réponses (un nombre entre 0 et 1).
Calculez ce score et affichez-le sous forme de pourcentage arrondi.
"""

# TODO : calculez le score avec modele.score(X_test, y_test)
# TODO : affichez le résultat en pourcentage
score = modele.score(X_test, y_test)
print(score)
print("Pourcentage de bonnes réponses :", round(score * 100), "%")

"""### Question 7.2 : Observer les premières prédictions en direct
Regardons ce que prédit concrètement l'IA sur les 5 premiers e-mails du jeu de test.
"""

X_test_list = list(X_test)
y_test_list = list(y_test)
predictions = modele.predict(X_test)

for i in range(5):
    vrai = "PHISHING (1)" if y_test_list[i] == 1 else "LÉGITIME (0)"
    devine = "PHISHING (1)" if predictions[i] == 1 else "LÉGITIME (0)"
    statut = "✅ Correct" if vrai == devine else "❌ Erreur"
    print(f"Message {i+1} : {statut}")
    print(f"  Vrai : {vrai} | IA a deviné : {devine}")
    print("  Extrait :", X_test_list[i][:75], "...")
    print()

"""---
## 8. L'esprit critique de l'analyste SOC : Où l'IA hésite-t-elle ?
En cybersécurité, une IA ne doit jamais être considérée comme infaillible.
Le modèle ne donne pas seulement un verdict binaire : il calcule aussi une **probabilité de phishing** (entre 0% et 100%).
- Une probabilité proche de **100 %** : l'IA est formelle, c'est du phishing.
- Une probabilité proche de **0 %** : l'IA est sûre que le message est légitime.
- Une probabilité proche de **50 %** : **l'IA hésite complètement !** C'est souvent sur des e-mails ambigus ou mal rédigés.
"""

import numpy as np

# Calcul de la probabilité d'être du phishing pour chaque e-mail de test
proba_phishing = modele.predict_proba(X_test)[:, 1]

# Mesure de l'hésitation : plus la valeur est proche de 0, plus l'IA hésite à 50%
hesitation = np.abs(proba_phishing - 0.5)
ordre_hesitation = np.argsort(hesitation)

print("Top 5 des e-mails où l'IA a le plus d'incertitude :")
print("=" * 70)
for i in ordre_hesitation[:5]:
    confiance = round(proba_phishing[i] * 100, 1)
    print(f"Probabilité phishing : {confiance}% | Réel : {y_test_list[i]}")
    print("Texte :", X_test_list[i][:80], "...")
    print("-" * 70)

"""---
## 9. Bonus (Exercice 3.2) : Les mots qui trahissent le phishing
Comment l'IA prend-elle ses décisions ?
En régression logistique, chaque mot du vocabulaire reçoit un **coefficient (poids)** :
- Un poids **positif élevé** : le mot pousse fortement vers le diagnostic de **phishing**.
- Un poids **négatif** : le mot rassure l'IA et évoque un e-mail **légitime**.
"""

import numpy as np

# Récupération du vocabulaire et des coefficients appris par le modèle
vectoriseur = modele.named_steps["tfidfvectorizer"]
classifieur = modele.named_steps["logisticregression"]

mots = np.array(vectoriseur.get_feature_names_out())
poids = classifieur.coef_[0]

# Tri des mots par poids
top_phishing = mots[np.argsort(poids)[-5:]]
top_legitime = mots[np.argsort(poids)[:5]]

print("🚨 Top 10 des mots qui évoquent le PHISHING :")
print(list(top_phishing)[::-1])
print()
print("✅ Top 10 des mots qui évoquent un e-mail LÉGITIME :")
print(list(top_legitime))

"""---
## Bilan de la journée
Félicitations ! Vous avez franchi un cap majeur :
1. Vous savez ce qu'est un **DataFrame Pandas** (`head`, `tail`, `shape`, `columns`).
2. Vous savez inspecter les données avec `.value_counts()` et des **filtres conditionnels**.
3. Vous avez enrichi vos données en créant de **nouvelles colonnes** (`df["longueur"]`, `.str.contains`).
4. Vous avez respecté la méthodologie rigoureuse du Machine Learning avec **Train / Test split**.
5. Vous avez entraîné un **pipeline TF-IDF + Régression logistique** capable de classifier des e-mails en une fraction de seconde !
6. Vous avez exploré ses **probabilités d'hésitation** et compris les **mots clés** qu'il privilégie.

Au **Jour 4**, nous allons transformer ce modèle en un véritable outil opérationnel :
nous écrirons la fonction `predire(email)` pour tester des e-mails saisis au clavier et nous déploierons le tout dans une **application web interactive Streamlit** !
"""